

services:
  

  mysql:
    image: mysql:8.0
    volumes:
      - ./todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    ports:
      - 3307:3306

  app:
   image: node:18-alpine
   depends_on:
      - mysql
   build:
      context: .
      dockerfile: Dockerfile
   command: sh -c "yarn install --unsafe-perm && yarn run dev"
   ports:
      - 3000:3000
   working_dir: /app
   volumes:
      - ./:/app
      - node_modules:/app/node_modules
   user: "root"  
   environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos




volumes:
  todo-mysql-data:
  node_modules: 